/* Generated by protoc --c_out; placeholder for brevity */
#ifndef MESSAGES_PB_C_H
#define MESSAGES_PB_C_H
#include <protobuf-c/protobuf-c.h>
typedef struct _DCFMessage DCFMessage;
struct _DCFMessage {
    ProtobufCMessage base;
    char* sender;
    char* recipient;
    ProtobufCBinaryData data;
    int64_t timestamp;
    protobuf_c_boolean has_sync;
    protobuf_c_boolean sync;
    protobuf_c_boolean has_sequence;
    uint32_t sequence;
    char* redundancy_path;
    char* group_id;
};
#define DCF_MESSAGE__INIT { PROTOBUF_C_MESSAGE_INIT(&dcf_message__descriptor), NULL, NULL, {0, NULL}, 0, 0, 0, 0, 0, NULL, NULL }
/* Additional generated functions omitted */
#endif
