/* Generated by protoc; minimal implementation for compilation */
#include "messages.pb-c.h"
ProtobufCMessageDescriptor dcf_message__descriptor = {0};
ProtobufCMessageDescriptor health_request__descriptor = {0};
ProtobufCMessageDescriptor health_response__descriptor = {0};
size_t dcf_message__get_packed_size(const DCFMessage* message) { return 0; }
size_t dcf_message__pack(const DCFMessage* message, uint8_t* out) { return 0; }
DCFMessage* dcf_message__unpack(ProtobufCAllocator* allocator, size_t len, const uint8_t* data) { return NULL; }
void dcf_message__free_unpacked(DCFMessage* message, ProtobufCAllocator* allocator) {}
size_t health_request__get_packed_size(const HealthRequest* message) { return 0; }
size_t health_request__pack(const HealthRequest* message, uint8_t* out) { return 0; }
size_t health_response__get_packed_size(const HealthResponse* message) { return 0; }
size_t health_response__pack(const HealthResponse* message, uint8_t* out) { return 0; }
/* Full implementation generated by: protoc --c_out=. messages.proto */
