#ifndef DCF_ERROR_H
#define DCF_ERROR_H

typedef enum {
    DCF_SUCCESS = 0,
    DCF_ERR_NULL_PTR,
    DCF_ERR_MALLOC_FAIL,
    DCF_ERR_CONFIG_NOT_FOUND,
    DCF_ERR_CONFIG_INVALID,
    DCF_ERR_NETWORK_FAIL,
    DCF_ERR_SERIALIZATION_FAIL,
    DCF_ERR_DESERIALIZATION_FAIL,
    DCF_ERR_PLUGIN_FAIL,
    DCF_ERR_INVALID_STATE,
    DCF_ERR_ROUTE_NOT_FOUND,
    DCF_ERR_GRPC_FAIL,
    DCF_ERR_INVALID_ARG,
    DCF_ERR_CONFIG_UPDATE_FAIL,
    DCF_ERR_UNKNOWN
} DCFError;

const char* dcf_error_str(DCFError err);

#endif
